#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR='vim'

# Customize to your needs...

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

export ERL_AFLAGS="-kernel shell_history enabled"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/bin/dev.sh ] && source ~/bin/dev.sh && compdef _dev dev

[ -f ~/bin/_rg.sh ] && source ~/bin/_rg.sh && compdef _rg rg

PATH=~/bin:$PATH
PATH=~/.local/bin:$PATH

# eval "$(hub alias -s)"

eval "$(fasd --init auto)"

# Aliases

alias v='f -e vim'
alias :q=exit
alias q=exit
alias ed='ed -p:'
alias be='bundle exec'
alias bx='bundle exec'
alias rg='rg --no-messages'
alias cx='convox'

if { [ -n "$TMUX" ]; } then
  clear-pane-title
fi

