#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

eval "$(mise activate zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

ulimit -n 4096

PATH=~/bin:$PATH
export PATH="/opt/homebrew/bin:$PATH"

GPG_TTY=$(tty)
export GPG_TTY

# Customize to your needs...

autoload bashcompinit
bashcompinit

export ERL_AFLAGS="-kernel shell_history enabled"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_DEFAULT_OPTS='--preview "bat --style=numbers --color=always {} | head -200"'

source <(fzf --zsh)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/bin/dev.sh ] && source ~/bin/dev.sh && compdef _dev dev && compdef _devsm devsm

[ -f ~/bin/_rg.sh ] && source ~/bin/_rg.sh && compdef _rg rg

PATH=~/.local/bin:$PATH

PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

PATH="/Users/trevorfenn/Library/Python/2.7/bin:$PATH"

# Aliases

alias v='f -e vim'
alias :q=exit
alias q=exit
alias ed='ed -p:'
alias rg='rg --no-messages'
# alias cat='bat'

# if { [ -n "$TMUX" ]; } then
#   clear-pane-title
# fi

export GIT_MERGE_AUTOEDIT=no
